// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/QuizLyM.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class QuizLyM {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object getFirstAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=6;
      Object Q=$fix(GCollections.asSet("A","B","C","0","err","F","I"));
      $line=7;
      Object \u03A3=$fix(GCollections.asSet('a','b','c','#','$'));
      $line=8;
      Object q_0=$fix("I");
      $line=9;
      Object F=$fix(GCollections.asSet("F"));
      $line=10;
      Object \u03B4=$fix(new Object[]{new Object[]{"I",'a',"A"},new Object[]{"I",'b',"B"},new Object[]{"I",'c',"C"},new Object[]{"A",'a',"0"},new Object[]{"A",'b',"err"},new Object[]{"A",'c',"err"},new Object[]{"B",'a',"err"},new Object[]{"B",'c',"err"},new Object[]{"C",'a',"err"},new Object[]{"C",'b',"err"},new Object[]{"A",'$',"err"},new Object[]{"B",'$',"err"},new Object[]{"C",'$',"err"},new Object[]{"0",'$',"F"},new Object[]{"F",'a',"err"},new Object[]{"F",'b',"err"},new Object[]{"F",'c',"err"},new Object[]{"F",'$',"err"},new Object[]{"I",'$',"F"},new Object[]{"I",'#',"err"},new Object[]{"0",'a',"A"},new Object[]{"A",'#',"I"},new Object[]{"B",'b',"0"},new Object[]{"0",'b',"B"},new Object[]{"B",'#',"I"},new Object[]{"C",'c',"0"},new Object[]{"0",'c',"C"},new Object[]{"0",'#',"I"},new Object[]{"C",'#',"I"},new Object[]{"err",'#',"err"},new Object[]{"err",'a',"err"},new Object[]{"err",'b',"err"},new Object[]{"err",'c',"err"},new Object[]{"err",'$',"err"},new Object[]{"F",'#',"err"}});
      $line=46;
      $result=$invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q_0,F,\u03B4});
      if (true) break $try;
      $line=47;
      $rethrow(new RuntimeException("The function \"getFirstAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,QuizLyM.class,"getFirstAutomaton",$line);
    }
    return $result;
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=49;
      IAutomaton M_1=null;
      M_1=$defaultValue(IAutomaton.class);
      $line=50;
      M_1=$cast(IAutomaton.class,$fix(QuizLyM.getFirstAutomaton()));
      $line=51;
      GAutomataFrame frame=null;
      frame=$invokeConstructor(GAutomataFrame.class,new Object[]{});
      $line=52;
      ((gold.visualization.automaton.GAutomataFrame)frame).display($cast(java.lang.String.class,"1a"),$cast(gold.structures.automaton.IAutomaton.class,M_1));
      $line=53;
      ((gold.visualization.automaton.GAutomataFrame)frame).setVisible($bool(true));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,QuizLyM.class,"main",$line);
    }
  }
}
